何故何故分析を新規作成する機能を実装しました
kaori23/whywhyanalysis pull request #2
Opened 2020-11-29 13:49 UTC by kaori23

## 実装内容概要
・何故何故分析を新規作成する機能を追加

## 実装詳細
レイアウト(View)
　以下4画面を追加
　・ホーム画面
　・何故何故分析新規追加画面
　・何故何故分析新規追加確認画面
　・ホーム画面に何故何故分析を一覧表示するためのカスタムセル画面

Model
　・WhywhyAnalysisのモデルを新規追加
　・DBにアクセスするクラス(以下機能を実装)を新規追加
　　・DBにWhywhyAnalysis型のデータを格納する機能
　　・DBに格納されたWhywhyAnalysis型のデータを全権取得する機能　
　
Contoller
　・ホーム画面に何故何故分析一覧を表示するクラスを新規追加
　・何故何故分析新規追加処理を行うクラスを新規追加

## レビュー時の注意点
未実装の内容
　レイアウトについて
　　デザインとの差異がありますが、後日対応するため現在は確認されなくて結構です。

2020-11-29 23:05 UTC, tomoki-inoue1221 requested changes
2点指摘箇所あるので確認お願いします！

2020-11-29 23:05 UTC, tomoki-inoue1221 commented on whywhyanalysisApp/Utility/ValidateUtility.swift
> +            }
text.isNotEmptyをreturnで良いと思います！

2020-11-29 23:05 UTC, tomoki-inoue1221 commented on whywhyanalysisApp/View/AnalysisListCustumCell.swift
> +//
不要なら削除しちゃいましょう！

2020-11-30 11:48 UTC, kaori23 commented on whywhyanalysisApp/Utility/ValidateUtility.swift
> +            }
isEmptyを使用する方針に変更しました。

2020-11-30 11:48 UTC, kaori23 commented on whywhyanalysisApp/View/AnalysisListCustumCell.swift
> +//
削除しました。

2020-11-30 12:03 UTC, tomoki-inoue1221 approved these changes
指摘と言うレベルではないのですが、こちらの方がいいのでは？
というものを書いておきました。
必須ではないと思うので、好き好きで編集してください！👍

2020-11-30 12:03 UTC, PictoMki commented on whywhyanalysisApp/Utility/ValidateUtility.swift
> +        return flag
個人的には無駄に変数を宣言するのは好きじゃないので、
以下のコードの方が良い気がします。
```
if let optinalText = optinalText {
// 空白文字を削除
let text = optinalText.trimmingCharacters(in: .whitespacesAndNewlines)
return !text.isEmpty
}
return false
```

2020-11-30 12:03 UTC, tomoki-inoue1221 commented on whywhyanalysisApp/Utility/ValidateUtility.swift
> +        return flag
```
flag = text.isEmpty
```

追加でこちらだとtextが空文字のときtrueになりますが大丈夫ですか？

2020-11-30 12:03 UTC, tomoki-inoue1221 commented on whywhyanalysisApp/Utility/ValidateUtility.swift
>      static func textEmplyCheck(optinalText: String?) -> Bool {
最初の指摘で気づけていればよかったのですが、
こちらの関数名だとtrueの時に空白なのか、falseの時に空白なのか少しわかりづらいかもです。

bool値を返す関数や変数は
isなんとか
canなんとか
などの命名が多いので、そちらに寄せるのがいいかなと思います。

2020-11-30 12:14 UTC, kaori23 commented on whywhyanalysisApp/Utility/ValidateUtility.swift
>      static func textEmplyCheck(optinalText: String?) -> Bool {
アドバイスありがとうございます。
関数名をisTextNotEmplyCheckに変更しました。

2020-11-30 12:15 UTC, kaori23 commented on whywhyanalysisApp/Utility/ValidateUtility.swift
> +        return flag
ご指摘ありがとうございます。
!text.isEmptyに修正しました。

2020-11-30 12:56 UTC, merged