作成済みの何故何故分析を編集する機能を実装しました
kaori23/whywhyanalysis pull request #4
Opened 2020-12-19 10:26 UTC by kaori23

## 実装内容概要
・なぜなぜ分析の編集機能を追加

## 実装詳細
・モデル.WhywhyAnalysisに
　・項目.ステータス、何故何故分析Noを追加（モデルクラスの編集)
　・主キーを追加

・カスタムセル .AnalysisListCustumCellに項目.ステータスを追加(画面編集)
・メインストーリーボード.Main.storyboardに項目.ステータスを追加(画面編集)

・コントローラー.RegistAnalysisViewControllerに項目.ステータスの処理(UIPickerView)を追加
・コントローラー.EditAnalysisViewControllerに項目.ステータスの処理を追加
・コントローラー.HomeViewControllerに項目.ステータスの処理を追加

・データベース編集.DataStorageに
　・メソッド.何故何故分析を編集、メソッド.特定の何故何故分析を取得を追加
　・メソッド.新規何故何故分析を追加に何故何故分析No.の処理を追加

## レビュー時の注意点
未実装部分
・デザインについては未実装です

レビュー時に注意して欲しいこと
以下を重点的に見ていただきたいです。
　・変数名やファイル名について適切な名前であるか
　・保守性(拡張性)の高いソースであるか(特にRegistAnalysisViewControllerを見ていただきたいです)
※ご指摘いただいた部分は今回、またはリファクタリングのタイミングで取り込みます。

以上、よろしくお願いいたします。

2020-12-19 13:37 UTC, tomoki-inoue1221 requested changes
EditAnalysisViewController.swiftというファイル名が
編集という名前が入ってるので、新規作成も兼ねているということが分かりづらいです！

コードを共通化することは大事ですが、コードの可読性が悪くなりそうな書き方は
なるべく控えた方がいいので少し意識してみてください！

2020-12-19 13:37 UTC, tomoki-inoue1221 commented on whywhyanalysisApp/Model/DataStorage.swift
> +        analysis.whywhyAnalysisNo = maxWhywhyAnalysisNo + 1
ここのコードが少し難しいので、
```
let maxWhywhyAnalysis = try! Realm().objects(WhywhyAnalysis.self).sorted(byKeyPath: "whywhyAnalysisNo").last?.whywhyAnalysisNo
// タスク初作成の場合
if let newAnalysisNo = maxWhywhyAnalysisNo {
    analysis.whywhyAnalysisNo = maxWhywhyAnalysisNo + 1
} else {
    analysis.whywhyAnalysisNo = 1
}
```
とかの方がコードは長くなりますが、自明でわかりやすいかなとおもいます。

2020-12-19 13:37 UTC, tomoki-inoue1221 commented on whywhyanalysisApp/Controller/RegistAnalysisViewController.swift
> +        self.statusPickerView.selectRow(statusNum, inComponent: 0, animated: false)
こちらのコードの意図がわからないのですが、
なんのための実装でしょうか？

2020-12-19 13:37 UTC, tomoki-inoue1221 commented on whywhyanalysisApp/Controller/EditAnalysisViewController.swift
> +            }
こちらインスタンス生成を共通化したことによって
変数名と処理の場合わけが分かりづらくなっています。

①新規作成の場合
WhywhyAnalysisのインスタンスを新規作成
②編集の場合
渡されたインスタンスに対して、変更内容を適用

上記のように書いた方が分かりやすいと思います

2020-12-20 03:26 UTC, kaori23 commented on whywhyanalysisApp/Controller/RegistAnalysisViewController.swift
> +        self.statusPickerView.selectRow(statusNum, inComponent: 0, animated: false)
こちらはPickerViewの初期表示編集部分となります。
①何故何故分析を新規作成する場合、ステータスは実施中
②何故何故分析を編集する場合、登録済み(編集前)のステータスを表示するように編集しています。

実装理由：
何故何故分析を編集する場合、こちらの編集をしない限り一律で実施中が初期表示となります。
ステータスだけ登録内容を反映させないことに違和感を感じたので編集するように実装しました。

2020-12-20 07:00 UTC, kaori23 commented on whywhyanalysisApp/Model/DataStorage.swift
> +        analysis.whywhyAnalysisNo = maxWhywhyAnalysisNo + 1
アドバイスありがとうございます。
おっしゃる通りご提示いただいたソースの方が可読性が高いと思うので修正します。

2020-12-20 08:03 UTC, kaori23 commented on whywhyanalysisApp/Controller/EditAnalysisViewController.swift
> +            }
こちらは新規作成する場合、編集する場合も同じ処理となる為共通化しています。

編集する場合、ホーム画面から値渡ししたwhywhyAnalysisを編集後の内容に代入する場合、トランザクションエラーとなります。
これはwhywhyAnalysisがRealmから取得したものであるからです。このエラーを解決するためにはトランザクション処理をする必要があります。
この画面は一時保存画面である為ここで更新処理は行わない為エラー解決はできないという認識です。
上記理由により編集する場合でも新規インスタンスを精製しています。

2020-12-20 22:21 UTC, tomoki-inoue1221 commented on whywhyanalysisApp/Controller/RegistAnalysisViewController.swift
> +        self.statusPickerView.selectRow(statusNum, inComponent: 0, animated: false)
なるほど、以下気になった点を念のためあげます。
①statusとstatusNumで状態を2重で管理しているので、statusがいらないと思います。(statusNumがわかれば配列から値がわかるはず)

②for文の部分をindex関数を使う
https://qiita.com/tikidunpon/items/9c458bfdc66bce04da20
配列操作の関数は基本的に意図がわかる関数を使う方がいいです。
用意されてる関数の組み合わせなどでうまく行かない場合以外はfor文はあまり使いません。

2020-12-21 14:15 UTC, kaori23 commented on whywhyanalysisApp/Controller/RegistAnalysisViewController.swift
> +        self.statusPickerView.selectRow(statusNum, inComponent: 0, animated: false)
①について
二重管理となっている理由についてですがUIPickerViewを利用していることが原因です。
statusNumは上述した理由、statusはUIPickerViewが選択された場合選択された文字列が返される為statusで管理しています。

②についてご指摘ありがとうございます。
    調べた結果配列で指定した要素のindex取得は配列.firstIndex(of: )の形が適切だと思うのでこちらの関数を用いることにします。

2020-12-22 01:39 UTC, tomoki-inoue1221 approved these changes
👍

2020-12-22 13:09 UTC, merged